# Generated by Django 4.0.3 on 2022-06-07 08:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_accesstimeoutlogs_oplogs_alter_admin_create_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financial_Commissioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=datetime.datetime(2022, 6, 7, 8, 43, 38, 296409, tzinfo=utc), verbose_name='入职时间')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('sex', models.CharField(max_length=2, verbose_name='性别')),
                ('account', models.CharField(max_length=16, verbose_name='账号')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('job', models.CharField(max_length=10, verbose_name='职位')),
            ],
            options={
                'db_table': 't_financial_commissioner',
            },
        ),
        migrations.AlterField(
            model_name='admin',
            name='create_time',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 6, 7, 8, 43, 38, 295412, tzinfo=utc), verbose_name='入职时间'),
        ),
        migrations.AlterField(
            model_name='departmanger',
            name='create_time',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 6, 7, 8, 43, 38, 294415, tzinfo=utc), verbose_name='入职时间'),
        ),
        migrations.AlterField(
            model_name='effictive_users',
            name='contract_amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='合同金额'),
        ),
        migrations.AlterField(
            model_name='effictive_users',
            name='create_time',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 6, 7, 8, 43, 38, 295412, tzinfo=utc), verbose_name='入库时间'),
        ),
        migrations.AlterField(
            model_name='effictive_users',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='发放金额'),
        ),
        migrations.AlterField(
            model_name='general_manager',
            name='create_time',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 6, 7, 8, 43, 38, 295412, tzinfo=utc), verbose_name='入职时间'),
        ),
        migrations.AlterField(
            model_name='job_log',
            name='create_time',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 6, 7, 8, 43, 38, 295412, tzinfo=utc), verbose_name='日志创建时间'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='create_time',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 6, 7, 8, 43, 38, 293417, tzinfo=utc), verbose_name='入职时间'),
        ),
        migrations.AlterField(
            model_name='salesdirector',
            name='create_time',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 6, 7, 8, 43, 38, 294415, tzinfo=utc), verbose_name='入职时间'),
        ),
        migrations.AlterField(
            model_name='users',
            name='create_time',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 6, 7, 8, 43, 38, 293417, tzinfo=utc), verbose_name='入库时间'),
        ),
        migrations.AlterField(
            model_name='users_conversation',
            name='create_time',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 6, 7, 8, 43, 38, 294415, tzinfo=utc), verbose_name='入库时间'),
        ),
    ]
