# Generated by Django 4.0.3 on 2022-06-09 06:06

import Users.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_effictive_users_contract_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='create_time',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 6, 9, 6, 6, 9, 763515, tzinfo=utc), verbose_name='入职时间'),
        ),
        migrations.AlterField(
            model_name='departmanger',
            name='create_time',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 6, 9, 6, 6, 9, 762518, tzinfo=utc), verbose_name='入职时间'),
        ),
        migrations.AlterField(
            model_name='effictive_users',
            name='create_time',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 6, 9, 6, 6, 9, 764512, tzinfo=utc), verbose_name='入库时间'),
        ),
        migrations.AlterField(
            model_name='financial_commissioner',
            name='create_time',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 6, 9, 6, 6, 9, 765509, tzinfo=utc), verbose_name='入职时间'),
        ),
        migrations.AlterField(
            model_name='general_manager',
            name='create_time',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 6, 9, 6, 6, 9, 764512, tzinfo=utc), verbose_name='入职时间'),
        ),
        migrations.AlterField(
            model_name='job_log',
            name='create_time',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 6, 9, 6, 6, 9, 764512, tzinfo=utc), verbose_name='日志创建时间'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='create_time',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 6, 9, 6, 6, 9, 762518, tzinfo=utc), verbose_name='入职时间'),
        ),
        migrations.AlterField(
            model_name='salesdirector',
            name='create_time',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 6, 9, 6, 6, 9, 763515, tzinfo=utc), verbose_name='入职时间'),
        ),
        migrations.AlterField(
            model_name='users',
            name='create_time',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 6, 9, 6, 6, 9, 762518, tzinfo=utc), verbose_name='入库时间'),
        ),
        migrations.AlterField(
            model_name='users_conversation',
            name='create_time',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 6, 9, 6, 6, 9, 763515, tzinfo=utc), verbose_name='入库时间'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_time', models.DateTimeField(auto_created=datetime.datetime(2022, 6, 9, 6, 6, 9, 765509, tzinfo=utc), verbose_name='合同上传时间')),
                ('contract_name', models.CharField(max_length=50, verbose_name='合同名称')),
                ('contract_number', models.CharField(default='xxx', max_length=100, verbose_name='合同编号')),
                ('contract_money', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='合同金额')),
                ('contract_image', models.ImageField(blank=True, null=True, upload_to=Users.models.contract_directory_path, verbose_name='身份证')),
                ('effictiveusers_id', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='c_Contract', to='Users.effictive_users')),
            ],
            options={
                'db_table': 't_contract',
            },
        ),
    ]
