# Generated by Django 4.0.3 on 2022-06-09 06:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_alter_admin_create_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='effictive_users',
            name='job',
            field=models.CharField(default='xxx', max_length=11, verbose_name='职业'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='create_time',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 6, 9, 6, 41, 31, 658007, tzinfo=utc), verbose_name='入职时间'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_time',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 6, 9, 6, 41, 31, 665985, tzinfo=utc), verbose_name='合同上传时间'),
        ),
        migrations.AlterField(
            model_name='departmanger',
            name='create_time',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 6, 9, 6, 41, 31, 654014, tzinfo=utc), verbose_name='入职时间'),
        ),
        migrations.AlterField(
            model_name='effictive_users',
            name='create_time',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 6, 9, 6, 41, 31, 659004, tzinfo=utc), verbose_name='入库时间'),
        ),
        migrations.AlterField(
            model_name='financial_commissioner',
            name='create_time',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 6, 9, 6, 41, 31, 665985, tzinfo=utc), verbose_name='入职时间'),
        ),
        migrations.AlterField(
            model_name='general_manager',
            name='create_time',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 6, 9, 6, 41, 31, 659004, tzinfo=utc), verbose_name='入职时间'),
        ),
        migrations.AlterField(
            model_name='job_log',
            name='create_time',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 6, 9, 6, 41, 31, 659004, tzinfo=utc), verbose_name='日志创建时间'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='create_time',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 6, 9, 6, 41, 31, 653017, tzinfo=utc), verbose_name='入职时间'),
        ),
        migrations.AlterField(
            model_name='salesdirector',
            name='create_time',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 6, 9, 6, 41, 31, 658007, tzinfo=utc), verbose_name='入职时间'),
        ),
        migrations.AlterField(
            model_name='users',
            name='create_time',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 6, 9, 6, 41, 31, 653017, tzinfo=utc), verbose_name='入库时间'),
        ),
        migrations.AlterField(
            model_name='users_conversation',
            name='create_time',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 6, 9, 6, 41, 31, 658007, tzinfo=utc), verbose_name='入库时间'),
        ),
    ]
