# Generated by Django 4.0.3 on 2022-06-09 07:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0014_accountant_alter_admin_create_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='effictive_users',
            name='service_fee_number',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='服务费'),
        ),
        migrations.AddField(
            model_name='effictive_users',
            name='service_fee_status',
            field=models.BooleanField(default=False, verbose_name='是否收取服务费'),
        ),
        migrations.AlterField(
            model_name='accountant',
            name='create_time',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 6, 9, 7, 8, 21, 753891, tzinfo=utc), verbose_name='入职时间'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='create_time',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 6, 9, 7, 8, 21, 751896, tzinfo=utc), verbose_name='入职时间'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_time',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 6, 9, 7, 8, 21, 753891, tzinfo=utc), verbose_name='合同上传时间'),
        ),
        migrations.AlterField(
            model_name='departmanger',
            name='create_time',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 6, 9, 7, 8, 21, 750900, tzinfo=utc), verbose_name='入职时间'),
        ),
        migrations.AlterField(
            model_name='effictive_users',
            name='create_time',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 6, 9, 7, 8, 21, 751896, tzinfo=utc), verbose_name='入库时间'),
        ),
        migrations.AlterField(
            model_name='financial_commissioner',
            name='create_time',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 6, 9, 7, 8, 21, 752894, tzinfo=utc), verbose_name='入职时间'),
        ),
        migrations.AlterField(
            model_name='general_manager',
            name='create_time',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 6, 9, 7, 8, 21, 751896, tzinfo=utc), verbose_name='入职时间'),
        ),
        migrations.AlterField(
            model_name='job_log',
            name='create_time',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 6, 9, 7, 8, 21, 751896, tzinfo=utc), verbose_name='日志创建时间'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='create_time',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 6, 9, 7, 8, 21, 749898, tzinfo=utc), verbose_name='入职时间'),
        ),
        migrations.AlterField(
            model_name='salesdirector',
            name='create_time',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 6, 9, 7, 8, 21, 750900, tzinfo=utc), verbose_name='入职时间'),
        ),
        migrations.AlterField(
            model_name='users',
            name='create_time',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 6, 9, 7, 8, 21, 749898, tzinfo=utc), verbose_name='入库时间'),
        ),
        migrations.AlterField(
            model_name='users_conversation',
            name='create_time',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 6, 9, 7, 8, 21, 750900, tzinfo=utc), verbose_name='入库时间'),
        ),
    ]
